module.exports = {
  "list" : [
    {
      name: "javascripting",
      owner: "sethvincent",
      menu: "contents",
      track: "core",
    },
    {
      name: "learnyounode",
      owner: "workshopper",
      menu: ["HELLO WORLD", "BABY STEPS", "MY FIRST I/O!", "MY FIRST ASYNC I/O!", "FILTERED LS", "MAKE IT MODULAR", "HTTP CLIENT", "HTTP COLLECT", "JUGGLING ASYNC", "TIME SERVER", "HTTP FILE SERVER", "HTTP UPPERCASERER", "HTTP JSON API SERVER"],
      track: "core",
    },
    {
      name: "scope-chains-closures",
      owner: "jesstelford",
      menu: ['scopes', 'scope-chains', 'global-scope-and-shadowing', 'closures', 'garbage-collection'],
      track: "electives",
    },
    {
      name: "functional-javascript-workshop",
      owner: "timoxley",
      menu: "contents/exercises",
      track: "electives",
      dirName: "functional-javascript",
    },
    {
      name: "planetproto",
      owner: "sporto",
      menu: "contents/exercises",
      track: "electives",
      numbered: true
    },
    {
      name: "regex-adventure",
      owner: "substack",
      menu: ['LITERALLY', 'ANCHOR START', 'ANCHOR END', 'CHARACTER CLASS', 'NEGATED CHARACTER CLASS', 'META', 'QUANTIFIER', 'SPLIT', 'CAPTURE', 'CAPTURE BREAKWORD', 'ALTERATION', 'QUANTIFIED GROUP', 'QUOTES', 'BLINK'],
      track: "electives",
    },
    {
      name: "async-you",
      owner: "bulkan",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "browserify-adventure",
      owner: "substack",
      menu: "contents",
      track: "electives",
    },
    {
      name: "bug-clinic",
      owner: "othiym23",
      menu: ['INTAKE', 'TRIAGE', 'DISINFECT', 'MONITOR', 'TRACES', 'TEST', 'SCAN', 'PROBE', 'OBSERVE', 'INTERVENE', 'OPERATE', 'BIOPSY', 'POSTMORTEM'],
      track: "electives",
    },
    {
      name: "bytewiser",
      owner: "maxogden",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "count-to-6",
      owner: "domenic",
      menu: "contents/lib/exercises",
      track: "electives",
    },
    {
      name: "esnext-generation",
      owner: "jesstelford",
      menu: ['introduction-to-iterators', 'built-in-iterators', 'advanced-iterables', 'introduction-to-generators', 'passing-args-to-yield'],
      track: "electives",
    },
    {
      name: "expressworks",
      owner: "azat-co",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "git-it",
      owner: "jlord",
      menu: "contents",
      track: "electives",
    },
    {
      name: "how-to-npm",
      owner: "npm",
      menu: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17],
      track: "electives",
    },
    {
      name: "learn-generators",
      owner: "isRuslan",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "learn-sass",
      owner: "claudiopro",
      menu: [
  "variables",
  "nesting",
  "imports",
  "mixins",
  "mixin_content",
  "extend_inheritance",
  "operators",
  "nested_properties",
  "parent_selector",
  "interpolation",
  "each",
  "for_loop",
  "while_loop"
],
      track: "electives",
    },
    {
      name: "learnyoumongo",
      owner: "evanlucas",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "learnyoureact",
      owner: "tako-black",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "lololodash",
      owner: "mdunisch",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "perfschool",
      owner: "bevacqua",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "promise-it-wont-hurt",
      owner: "stevekane",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "stream-adventure",
      owner: "substack",
      menu: "contents",
      track: "electives",
    },
    {
      name: "test-anything",
      owner: "finnp",
      menu: ['LOG IT OUT', 'TELL ME WHAT IS WRONG', 'TAPE IT TOGETHER', 'CALL ME MAYBE', 'TO ERR IS HUMAN, TO PURR FELINE'],
      track: "electives",
    },
    {
      name: "tower-of-babel",
      owner: "yosuke-furukawa",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "shader-school",
      owner: "stackgl",
      menu: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],
      track: "electives",
    },
    {
      name: "levelmeup",
      owner: "workshopper",
      menu: "contents",
      track: "electives",
    },
    {
      name: "makemehapi",
      owner: "hapijs",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "IntroToWebGLWithThreeJS",
      owner: "alexmackey",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "nodebot-workshop",
      owner: "tableflip",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "kick-off-koa",
      owner: "koajs",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "goingnative",
      owner: "workshopper",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "learnyoucouchdb",
      owner: "robertkowalski",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "webgl-workshop",
      owner: "stackgl",
      menu: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26],
      track: "electives",
    },
    {
      name: "learnuv",
      owner: "thlorenz",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "web-audio-school",
      owner: "mmckegg",
      menu: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],
      track: "electives",
    },
    {
      name: "torrential",
      owner: "No9",
      menu: "contents/exercises",
      track: "electives",
    },
    {
      name: "thinking-in-react",
      owner: "asbjornenge",
      menu: "contents/exercises",
      track: "electives",
    },
  ]
};